// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwtOQjxPnfTnktG4b_-bMDKAotKxw4604',
    appId: '1:16376572103:web:3d4b2acbe6c0e4d37cf6e2',
    messagingSenderId: '16376572103',
    projectId: 'farmer-89418',
    authDomain: 'farmer-89418.firebaseapp.com',
    storageBucket: 'farmer-89418.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdLPr1td75bSy4XYzf8Obk5aC3mP3GVjQ',
    appId: '1:16376572103:android:5decf9c9440a510d7cf6e2',
    messagingSenderId: '16376572103',
    projectId: 'farmer-89418',
    storageBucket: 'farmer-89418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_rZyjMF0a7my0eWcFg7rLS9LnRpGZxo',
    appId: '1:16376572103:ios:37b74a1537ff332b7cf6e2',
    messagingSenderId: '16376572103',
    projectId: 'farmer-89418',
    storageBucket: 'farmer-89418.appspot.com',
    iosBundleId: 'com.imran.krishfarm',
  );
}
